declare module 'react-native-ico-dazzle-line' {
    import { ReactNode } from 'react';
    import { SvgProps } from 'react-native-svg';

    type AdditionalProps = {
      onError?: (error: Error) => void;
      onLoad?: () => void;
      fallback?: ReactNode;
    };

    type iconNames = 'arrow-square-up' |
      'clipboard-user' |
      'distribute-spacing-horizontal-alt' |
      'frankenstein' |
      'phone-pause-alt' |
      'skull-crossbones' |
      'eye-slash-alt' |
      'star-alt-4' |
      'film' |
      'align-justify' |
      'headphones-alt' |
      'clapperboard-play' |
      'note-sticky' |
      'bracket-curly' |
      'vihara' |
      'border-right' |
      'cloud-xmark' |
      'objects-column' |
      'building' |
      'user-xmark-alt-1' |
      'sunrise' |
      'mailbox' |
      'code-pull-request' |
      'dial-med' |
      'arrow-narrow-circle-broken-up-right' |
      'arrow-circle-up' |
      'inbox-exclamation' |
      'pen-clip-slash' |
      'sun-dust' |
      'location-plus' |
      'message-circle-search' |
      'folder-exclamation' |
      'spider' |
      'table-cells-large' |
      'arrow-narrow-right-alignment' |
      'medal' |
      'file-dashed-line' |
      'moon' |
      'clapperboard' |
      'file-link' |
      'droplet' |
      'cloud-exclamation' |
      'atom' |
      'life-ring' |
      'bracket-round-right' |
      'switch-vertical' |
      'heat' |
      'file-check-alt' |
      'subscript' |
      'wallet-arrow-right' |
      'cloud-rainbow' |
      'house-chimney-floor' |
      'vial' |
      'user-block' |
      'floppy-disk-alt' |
      'cloud-snow-alt' |
      'cleaver-blood' |
      'money-withdrawal' |
      'tv-alt' |
      'presentation-chart' |
      'arrow-up-big-small' |
      'phone-slash-alt' |
      'mail-info' |
      'laptop-search-alt' |
      'shuffle' |
      'ball-pile' |
      'grid-vertical' |
      'message-square-question' |
      'caret-right-to-line' |
      'square' |
      'calendar' |
      'arrow-square-left' |
      'cloud-arrow-up' |
      'satellite-dish' |
      'calendar-arrow-down' |
      'pen-clip' |
      'credit-card-arrow-right-alt' |
      'file-heart' |
      'corner-right-up' |
      'clipboard-list' |
      'file-arrow-right' |
      'inbox-information' |
      'do-not-enter' |
      'message-circle-chat' |
      'volume-off' |
      'diagram-next' |
      'location-xmark' |
      'rectangle-terminal' |
      'bell-slash' |
      'code-compare' |
      'mail-check' |
      'user-plus-alt-1' |
      'bones' |
      'backward-step' |
      'filter-list' |
      'bell' |
      'caret-up' |
      'pentagon' |
      'refresh-cw' |
      'folder-info' |
      'inbox-alt-2' |
      'temperature-full' |
      'code-branch' |
      'jack-o-lantern' |
      'compass' |
      'file-redo' |
      'landmark-dome' |
      'glasses' |
      'rainbow' |
      'virus-covid-19' |
      'arrow-circle-down' |
      'image-minus' |
      'clock-twelve' |
      'calendar-day' |
      'user-question' |
      'sliders-up' |
      'clipboard-attachment' |
      'webcam-slash' |
      'laptop-dollar' |
      'circle-dots-horizontal' |
      'laptop-search' |
      'printer-alt' |
      'scythe' |
      'fingerprint-alt' |
      'presentation-chart-arrow' |
      'network-wired' |
      'circle-video' |
      'clock-six' |
      'user-alt-1' |
      'keyboard-alt' |
      'camcorder' |
      'calendar-heart' |
      'skull' |
      'phone-plus-alt' |
      'laptop-exclamation' |
      'h2' |
      'temperature-list' |
      'suitcase-medical' |
      'house-celcius' |
      'school' |
      'hospital-user' |
      'calendar-exclamation-alt' |
      'monitor-water' |
      'mail-lock' |
      'signature' |
      'id-badge' |
      'arrow-narrow-circle-broken-down-right' |
      'square-dazzle' |
      'chevron-up' |
      'award-alt' |
      'repeat-alt' |
      'message-circle-arrow-down' |
      'clock-eleven-thirty' |
      'message-circle-dots' |
      'laptop' |
      'expand-alt-1' |
      'lasso' |
      'laptop-check' |
      'backward-fast' |
      'message-circle-xmark' |
      'circle-microphone' |
      'signal-fair' |
      'file-question-alt-1' |
      'maximize' |
      'send-alt-2' |
      'snowman' |
      'sidebar' |
      'calendars' |
      'motorcycle' |
      'clarinet' |
      'temperature-low' |
      'pencil-slash' |
      'cash-register' |
      'message-square-refresh' |
      'refresh-ccw-alt' |
      'dial-med-low' |
      'yen-sign' |
      'monitor-alt-2' |
      'firewall' |
      'inbox-check' |
      'cookie-man' |
      'image-portrait' |
      'border-top-left' |
      'square-h' |
      'book' |
      'circle-half' |
      'arrow-left' |
      'location-pin-alt-1' |
      'chevron-up-left' |
      'location-arrow-alt' |
      'mail-block' |
      'prescription-bottle-medical' |
      'house-medical-check' |
      'mail-arrow-up' |
      'sensor-triangle-exclamation' |
      'dash' |
      'graduation-hat' |
      'files' |
      'laptop-alt-1' |
      'table-tree' |
      'snooze' |
      'arrow-narrow-circle-broken-up-left' |
      'message-square-plus' |
      'cube-alt-1' |
      'credit-card-alt' |
      'trophy' |
      'arrow-up-right' |
      'file-minus-alt' |
      'mail-xmark' |
      'arrow-up-a-z' |
      'house-window' |
      'industry-windows' |
      'diagram-subtask' |
      'globe' |
      'money-bill-stack' |
      'file-xmark-alt-1' |
      'battery-bolt' |
      'staff-snake' |
      'closed-captioning' |
      'receipt-alt' |
      'user-heart-alt-1' |
      'clock-seven-thirty' |
      'sipder-web' |
      'brackets-square' |
      'hat-wizard' |
      'sidebar-flip' |
      'signal-strong' |
      'clock' |
      'arrow-up-z-a' |
      'message-square-image' |
      'hourglass' |
      'wifi-exclamation' |
      'hurricane' |
      'battery-bolt-alt' |
      'arrow-right-from-arc' |
      'refresh-cw-alt-3' |
      'download' |
      'user-plus' |
      'watch' |
      'user-lock' |
      'paintbrush' |
      'laptop-alt' |
      'inbox-plus' |
      'square-exclamation' |
      'files-alt' |
      'sun' |
      'window-flip' |
      'mail-star' |
      'bags-shopping' |
      'file-plus-alt-1' |
      'book-user' |
      'seal-question' |
      'webcam-alt-1' |
      'circle-heat' |
      'bed' |
      'chevron-up-dot' |
      'calendar-minus' |
      'square-small' |
      'tablet-alt-1' |
      'minimize' |
      'tower-broadcast-slash' |
      'gallery-thumbnails' |
      'line-columns' |
      'portrait-user' |
      'bug-slash' |
      'battery-low' |
      'mail-exclamation' |
      'star' |
      'trash-plus-alt' |
      'headphones-alt-2' |
      'cloud-sun' |
      'draw-square-t' |
      'send' |
      'chart-waterfall' |
      'circle-location-arrow' |
      'stocking' |
      'ghost-smile' |
      'wine-glass' |
      'wreath' |
      'scale-balanced' |
      'money-check' |
      'file-horizontal' |
      'trash' |
      'sort' |
      'file-block-alt-1' |
      'heart-half' |
      'disc-alt' |
      'house-crack' |
      'file-info-alt' |
      'backpack-alt' |
      'wave-pulse' |
      'scrubber' |
      'square-medical' |
      'dazzling-star' |
      'lira-sign' |
      'skull-alt-1' |
      'receipt-alt-1' |
      'screen-users' |
      'mail-open-exclamation' |
      'send-alt-1' |
      'chart-line' |
      'files-alt-2' |
      'image' |
      'laptop-refresh-alt' |
      'clock-eight-thirty' |
      'calendar-alt' |
      'bluetooth-slash' |
      'chevron-selector-horizontal' |
      'halloween-calendar' |
      'arrow-up-wide-short' |
      'user-search-alt' |
      'signal-weak' |
      'pen-square' |
      'laptop-shield-alt' |
      'arrow-circle-right' |
      'location-crosshairs' |
      'list-check' |
      'chart-line-down' |
      'disc' |
      'school-flag' |
      'mobile-dollar' |
      'credit-card-plus' |
      'star-alt-3' |
      'bookmark' |
      'image-circle' |
      'memo' |
      'chart-pie-simple' |
      'link' |
      'cleaver' |
      'garage' |
      'nfc-symbol' |
      'minus' |
      'rotate-exclamation' |
      'battery-slash' |
      'arrow-narrow-down' |
      'gaming-pad-alt-1' |
      'building-lock' |
      'folder-plus' |
      'folder-arrow-up' |
      'clipboard-text-alt' |
      'arrow-right-to-bracket' |
      'light-emergency' |
      'door-open' |
      'mobile-bolt' |
      'mouse-alt-4' |
      'podium' |
      'bracket-square-right' |
      'brackets-curly' |
      'table-list' |
      'tower-observation' |
      'badge-percent' |
      'gift-alt' |
      'circle-parking-splash' |
      'cloche' |
      'wind-warning' |
      'corner-left-up' |
      'file-check-alt-1' |
      'user-plus-alt' |
      'mobile-alt-1' |
      'cloud-showers' |
      'shield-xmark' |
      'music-note' |
      'university' |
      'table' |
      'swatchbook' |
      'phone' |
      'lollipop' |
      'hat-witch' |
      'bolt' |
      'colors' |
      'clock-ten-thirty' |
      'enter' |
      'list-ul-alt-1' |
      'octagon' |
      'objects-align-top-alt' |
      'mountain-city' |
      'filter-slash' |
      'droplet-degree' |
      'square-user' |
      'tree-decorated-alt' |
      'heading' |
      'tent-arrow-down-to-line' |
      'code-fork' |
      'wifi-slash' |
      'mouse-alt-3' |
      'code-commit' |
      'map' |
      'mobile-signal' |
      'paperclip-slash' |
      'bullseye-arrow' |
      'arrow-narrow-right' |
      'video-arrow-down-left' |
      'chart-mixed-alt' |
      'clipboard-text' |
      'note-medical' |
      'arrow-sm-right' |
      'objects-align-right-alt' |
      'cloud-question' |
      'diamond-xmark' |
      'ruler' |
      'rectangle-vertical' |
      'building-ngo' |
      'circle-parking' |
      'skates' |
      'bridge-suspension' |
      'information-alt' |
      'pen-nib' |
      'mouse-alt-5' |
      'grid-horizontal' |
      'laptop-arrow-up-alt' |
      'van' |
      'temperature-snow' |
      'ruler-traingle' |
      'clock-four-thirty' |
      'laptop-xmark-alt' |
      'mail-open-alt' |
      'message-circle-chart-lines' |
      'simcard-slash' |
      'clock-lines' |
      'file-copy' |
      'dots-horizontal' |
      'moon-stars' |
      'square-kanban' |
      'folder-arrow-down' |
      'building-user' |
      'message-circle-list' |
      'hourglass-start' |
      'compress-wide' |
      'scale-unbalanced' |
      'lightbulb-alt' |
      'compress-alt-1' |
      'monitor-sun' |
      'arrow-narrow-down-move' |
      'umbrella' |
      'badge' |
      'sun-alt' |
      'traffic-light-go' |
      'heart-crack' |
      'lightbulb-exclamation' |
      'hexagon-alt-1' |
      'house-floor' |
      'star-alt-2' |
      'annotation' |
      'folder-arrow-left' |
      'dial-high' |
      'christmas-star' |
      'bat' |
      'traffic-light-stop' |
      'hashtag-lock' |
      'audio-description-slasg' |
      'user-shield' |
      'bracket-round' |
      'user-pen-alt' |
      'toilets-portable' |
      'house-smile' |
      'location-pin' |
      'mobile-check' |
      'tent-arrow-left-right' |
      'credit-card' |
      'halloween-mail-alt' |
      'user-lock-alt-1' |
      'user-pen-alt-1' |
      'distribute-spacing-vertical-alt' |
      'circle-quarters' |
      'shapes' |
      'file' |
      'diagram-project' |
      'calendar-arrow-up' |
      'martini-glass' |
      'file-search' |
      'arrow-spin' |
      'house-lock-alt' |
      'calendar-week' |
      'circle-bolt' |
      'power-bank' |
      'folder-question' |
      'warehouse-full' |
      'phone-pause' |
      'english-to-chinese' |
      'table-rows' |
      'image-square-check' |
      'prescription-bottle' |
      'message-circle-exclamation' |
      'cloud-snow' |
      'corner-down-right' |
      'coin-vertical' |
      'compress' |
      'grip-dots-vertical' |
      'drone' |
      'inbox-alt' |
      'table-list-alt' |
      'water' |
      'file-block' |
      'backpack' |
      'border-bottom' |
      'battery-mid' |
      'rectangles-mixed' |
      'battery-full' |
      'filter-xmark' |
      'file-redo-alt' |
      'border-top' |
      'hospitals' |
      'house-lock' |
      'sort-amount-up' |
      'face-id' |
      'wand-magic' |
      'rocket' |
      'map-location-pin' |
      'seal' |
      'chart-user-square' |
      'user' |
      'face-frown' |
      'align-left' |
      'money-insert' |
      'power-alt' |
      'coin-front' |
      'corner-up-left' |
      'arrow-square-up-left' |
      'laptop-lock' |
      'objects-align-left-alt' |
      'inbox-arrow-up' |
      'floppy-disk' |
      'speaker-alt-1' |
      'border-horizontal' |
      'arrow-narrow-bottom-alignment' |
      'files-alt-1' |
      'dots-vertical-alt' |
      'chevron-down-double' |
      'battery-exclamation' |
      'message-square-dots' |
      'overline' |
      'file-plus-alt' |
      'watch-alt-2' |
      'left-indent' |
      'arrow-square-down' |
      'kit-medical' |
      'octagon-exclamation' |
      'folder-minus' |
      'file-zipper' |
      'arrow-narrow-right-move' |
      'link-alt-1' |
      'hexagon' |
      'shield-check' |
      'check' |
      'file-pencil' |
      'notes' |
      'snow-blowing' |
      'water-arrow-down' |
      'candy-cane' |
      'backward' |
      'snowman-head' |
      'h1' |
      'clock-eight' |
      'house-tree' |
      'align-alt' |
      'folder-check' |
      'scissors' |
      'clock-xmark' |
      'objects-align-right' |
      'sun-haze' |
      'inbox-arrow-down' |
      'traffic-light-slow' |
      'flask-round-potion' |
      'balloon' |
      'mail-alt' |
      'sitemap' |
      'arrow-right-from-bracket' |
      'message-square-notification' |
      'cassette-tape' |
      'snow-alt' |
      'simcard-alt' |
      'message-circle-check' |
      'arrow-up-small-big' |
      'credit-card-arrow-right' |
      'chart-pie' |
      'user-question-alt' |
      'user-refresh-alt-1' |
      'circle-exclamation' |
      'anchor' |
      'sliders-simple' |
      'square-sliders' |
      'film-alt' |
      'annotation-user' |
      'plug' |
      'calendar-pen' |
      'sensor' |
      'chevron-selector-vertical' |
      'file-alt' |
      'file-code' |
      'phone-block' |
      'message-square-shield' |
      'ornament' |
      'lamp-desk' |
      'file-info' |
      'cloud-sleet' |
      'house-line' |
      'chevron-right-dot' |
      'shield-heart' |
      'compass-drafting' |
      'clock-five' |
      'plus-large' |
      'diagram-successor' |
      'briefcase-alt-2' |
      'location-check' |
      'compact-disc' |
      'train-tram' |
      'chevron-selector-horizontal-dot' |
      'poll-people' |
      'location-minus' |
      'folder-arrow-right' |
      'money-check-pen' |
      'sigma' |
      'chart-radar' |
      'message-circle-plus' |
      'search-alt' |
      'file-minus-alt-1' |
      'file-check' |
      'shield' |
      'key' |
      'temperature-quarter' |
      'window' |
      'bluetooth-signal' |
      'cake-christmas' |
      'building-exclamation' |
      'dots-vertical' |
      'arrow-down-z-a' |
      'house-chimney-blank' |
      'user-alt' |
      'garage-open' |
      'drum' |
      'arrow-narrow-circle-broken-left' |
      'tablet-alt' |
      'santa-glove' |
      'square-ring' |
      'audio-description' |
      'wifi-fair' |
      'christmas-candle' |
      'fork-spoon' |
      'text-width' |
      'list-ul' |
      'money-check-dollar-pen' |
      'search-minus' |
      'circle-yen' |
      'modem-alt-1' |
      'monitor-heart-rate' |
      'calendar-lines-alt' |
      'dice-five' |
      'house-fire' |
      'search-alt-1' |
      'arrow-sm-down' |
      'chevron-left-dot' |
      'house-bolt-alt' |
      'letter-chinese-a' |
      'message-circle-lines' |
      'coffin' |
      'archway' |
      'arrow-down-a-z' |
      'train-track' |
      'tv-alt-1' |
      'file-pencil-alt' |
      'message-square-arrow-down' |
      'mail-open-plus' |
      'delete-right' |
      'cedi-sign' |
      'shield-slash-alt-1' |
      'dial' |
      'money-bill' |
      'file-question-alt' |
      'cloud-up-arrow' |
      'buildings' |
      'webcam-alt-2' |
      'clipboard-arrow-down' |
      'party-bell' |
      'aperture' |
      'fence' |
      'pen' |
      'arrows-up-down' |
      'cookie' |
      'flashlight' |
      'tombstone-blank' |
      'trash-blank-alt' |
      'gift-card' |
      'album-collection' |
      'tree-plus' |
      'wand-magic-sparkles' |
      'speaker-alt' |
      'calculator' |
      'message-square-exclamation' |
      'layer-group' |
      'skull-alt' |
      'diagram-nested' |
      'trash-check-alt' |
      'triangle-exclamation' |
      'moon-cloud' |
      'folder-xmark' |
      'phone-plus' |
      'monitor-alt-1' |
      'notdef' |
      'tent' |
      'film-slash' |
      'file-shield' |
      'message-circle-shield' |
      'table-columns' |
      'tent-arrow-turn-left' |
      'monitor' |
      'chart-scatter' |
      'santa-hat-alt' |
      'chart-bar' |
      'colon-sign' |
      'link-alt' |
      'diagram-previous' |
      'signs-post' |
      'cloud-check' |
      'message-square-medical' |
      'filter' |
      'music-note-slash' |
      'mistletoe' |
      'phone-call' |
      'presentation-screen' |
      'lock' |
      'menorah' |
      'wifi-good' |
      'rectangle-code' |
      'move-left' |
      'book-sparkles' |
      'airplay' |
      'grip-dots' |
      'dice-four' |
      'objects-align-center-vertical-alt' |
      'cloud-wired' |
      'calendar-user' |
      'door-closed' |
      'circle-play' |
      'chart-simple' |
      'laptop-wired' |
      'receipt-alt-2' |
      'grid-circle' |
      'users' |
      'folder-lock' |
      'loop-vertical' |
      'message-square-lines' |
      'briefcase' |
      'weight' |
      'rectangle-wide' |
      'menu-alt-1' |
      'horizontal-rule' |
      'user-xmark-alt' |
      'clock-seven' |
      'folder-image' |
      'dial-low' |
      'laptop-lock-alt' |
      'file-search-alt' |
      'cart-shopping' |
      'caret-right' |
      'industry' |
      'frame' |
      'mask-face' |
      'clock-exclamation' |
      'dong-sign' |
      'align-center-justify' |
      'building-columns' |
      'pencil' |
      'user-question-alt-1' |
      'grip-lines-vertical' |
      'trash-check' |
      'chart-gantt' |
      'laptop-arrow-up' |
      'message-circle-question' |
      'palette' |
      'clock-six-thirty' |
      'mail-open-xmark' |
      'user-check' |
      'trash-undo-alt' |
      'house-flag' |
      'radiation' |
      'crop-simple' |
      'command' |
      'square-rss' |
      'circle-xmark' |
      'trash-plus' |
      'trash-slash' |
      'file-pencil-alt-1' |
      'search-plus' |
      'message-square-pencil' |
      'user-lock-alt' |
      'radio' |
      'hourglass-end' |
      'user-pen' |
      'mail-open-minus' |
      'list-music' |
      'mail-plus' |
      'clock-eleven' |
      'volume-xmark' |
      'message-circle-image' |
      'folder-user' |
      'message-circle-refresh' |
      'credit-card-alt-1' |
      'house-wifi' |
      'clock-twelve-thirty' |
      'signal-steam' |
      'inbox-alt-1' |
      'temperature-high' |
      'switch-horizontal' |
      'shield-slash' |
      'brush' |
      'hexagon-exclamation' |
      'sliders' |
      'crown' |
      'arrow-square-right' |
      'calendar-xmark' |
      'dial-min' |
      'location-pin-alt' |
      'text-height' |
      'projector' |
      'i-cursor' |
      'code-merge' |
      'globe-stand' |
      'temperature-empty' |
      'roller-coaster' |
      'circle-stop' |
      'calendar-plus-alt' |
      'gaming-pad' |
      'halloween-mail' |
      'square-phone' |
      'calendar-exclamation' |
      'mail-open-arrow-up' |
      'square-terminal' |
      'coins' |
      'message-square-search' |
      'calendar-days' |
      'chirstmas-star' |
      'certificate-check' |
      'laptop-shield' |
      'file-lock' |
      'phone-missed-alt' |
      'laptop-alt-2' |
      'image-square-xmark' |
      'file-contract' |
      'shield-dollar' |
      'chart-mixed' |
      'monitor-alt-6' |
      'pen-ruler' |
      'building-shield' |
      'teddy-bear' |
      'sort-down' |
      'bracket-curly-right' |
      'list-ol' |
      'exclamation' |
      'briefcase-dollar' |
      'bold' |
      'trash-clock' |
      'draw-square' |
      'file-redo-alt-1' |
      'document-layout-center' |
      'plus-minus' |
      'refresh-cw-alt' |
      'boombox' |
      'building-xmark' |
      'speaker' |
      'clock-ten' |
      'euro-circle' |
      'laptop-xmark' |
      'certificate' |
      'turkish-lira-sign' |
      'file-arrow-up' |
      'square-poll-horizontal' |
      'file-bookmark' |
      'file-arrow-down-alt' |
      'temperature-half' |
      'message-circle-block' |
      'car-battery' |
      'unlock' |
      'dice-six' |
      'ghost' |
      'objects-align-center-vertical' |
      'chart-network' |
      'square-poll-vertical' |
      'arrow-circle-down-right' |
      'arrows-left-right' |
      'rhombus' |
      'wallet' |
      'phone-flip' |
      'heart' |
      'seal-exclamation' |
      'file-arrow-up-alt' |
      'laptop-medical' |
      'arrow-right' |
      'phone-xmark' |
      'hexagon-check' |
      'star-sharp-half' |
      'user-minus-alt' |
      'square-user-check-alt' |
      'font-case' |
      'santa-hat' |
      'desktop-computer' |
      'paragraph' |
      'arrow-down-to-square' |
      'file-shredder' |
      'move-right' |
      'circle-plug' |
      'trash-list' |
      'circle-dashed' |
      'arrow-narrow-left-move' |
      'headphones' |
      'user-search-alt-1' |
      'dna' |
      'clock-three-thirty' |
      'file-block-alt' |
      'droplet-alt' |
      'inbox-star' |
      'user-heart' |
      'trash-clock-alt' |
      'information' |
      'bell-alt' |
      'train' |
      'gauge' |
      'droplet-slash' |
      'trash-xmark-alt' |
      'file-heart-alt' |
      'refresh-ccw-alt-1' |
      'reciept' |
      'spider-widow' |
      'diagram-sankey' |
      'clock-nine' |
      'border-left' |
      'phone-xmark-alt' |
      'cloud' |
      'treasure-chest' |
      'weight-scale' |
      'eye-dropper-full' |
      'circle-information' |
      'gold' |
      'coffin-open' |
      'sensor-fire' |
      'snow-alt-1' |
      'arrow-down-to-bracket' |
      'message-circle-notification' |
      'alarm-exclamation' |
      'austral-sign' |
      'refresh-ccw-alt-2' |
      'arrow-narrow-top-alignment' |
      'mask' |
      'airpods-alt' |
      'signal-slash' |
      'oil-well' |
      'handshake' |
      'phone-slash' |
      'cat' |
      'candy-corn' |
      'hourglass-half' |
      'bag-shopping' |
      'objects-align-bottom-alt' |
      'image-square' |
      'phone-block-alt' |
      'rocking-horse' |
      'farm' |
      'pen-circle' |
      'border-clear' |
      'flute' |
      'memo-pencil' |
      'arrow-circle-down-left' |
      'tents' |
      'ferris-wheel' |
      'xmark-large' |
      'refresh-cw-alt-1' |
      'crop' |
      'dollar-circle-list' |
      'file-exclamation-alt' |
      'file-xmark-alt' |
      'rotate' |
      'triangle-instrument' |
      'cctv' |
      'document-layout-right' |
      'chevron-down-dot' |
      'cloud-sun-alt' |
      'microscope' |
      'coffin-cross' |
      'message-circle-medical' |
      'message-square-check' |
      'cube-alt' |
      'star-sharp' |
      'square-check' |
      'arrow-down-1-9' |
      'signal-good' |
      'building-car' |
      'arrow-square-down-right' |
      'crow' |
      'forward' |
      'border-inner' |
      'code-pull-request-closed' |
      'arrow-rotate-right-24' |
      'rectangle-xmark' |
      'rotate-ccw' |
      'file-bookmark-alt-1' |
      'power-off' |
      'lights-holiday' |
      'shop' |
      'watch-alt' |
      'mail-minus' |
      'message-square-block' |
      'pen-field' |
      'fireplace' |
      'calendar-circle-plus' |
      'chart-scatter-3d' |
      'file-lock-alt' |
      'broom' |
      'flip-backward' |
      'square-dashed' |
      'square-minus' |
      'mail-open-info' |
      'file-plus' |
      'cloud-arrow-down' |
      'expand-alt-2' |
      'chart-pie-alt' |
      'halloween-calendar-bat' |
      'flask-round-blank' |
      'clipboard' |
      'flip-forward' |
      'cloud-bolt' |
      'cloud-rain' |
      'traffic-light' |
      'building-un' |
      'ban' |
      'check-double' |
      'gauge-low' |
      'tree-decorated-alt-1' |
      'battery-empty' |
      'user-block-alt-1' |
      'camera-alt-2' |
      'signature-lock' |
      'slash' |
      'trash-arrow-up' |
      'corner-left-down' |
      'image-plus' |
      'house-bolt' |
      'diagram-lean-canvas' |
      'file-user' |
      'volume-min' |
      'paperclip-alt' |
      'mail-heart' |
      'clock-one-thirty' |
      'arrow-down-wide-short' |
      'monitor-medical' |
      'cloud-lock' |
      'menu' |
      'hashtag' |
      'message-circle' |
      'box-archive' |
      'file-dollar-alt' |
      'bug' |
      'dialpad-square' |
      'square-user-check' |
      'light-emergency-on' |
      'cruzeiro-sign' |
      'christmas-bag' |
      'arrow-right-to-arc' |
      'book-open' |
      'city' |
      'arrow-down-small-big' |
      'circle-dots-vertical' |
      'truck' |
      'table-cells' |
      'paintbrush-alt' |
      'arrow-down-left' |
      'warehouse' |
      'bandage' |
      'eye-alt' |
      'trash-blank' |
      'scale-unbalanced-flip' |
      'rotate-cw' |
      'refresh-ccw-clock' |
      'arrow-narrow-up-move' |
      'user-shield-alt' |
      'chart-pie-alt-1' |
      'alarm-snooze' |
      'shield-minus' |
      'line-height' |
      'cloud-search' |
      'user-minus-alt-1' |
      'circle-exclamation-check' |
      'grid-plus' |
      'hard-drive' |
      'square-a-lock' |
      'menorah-alt-1' |
      'clipboard-plus' |
      'square-dollar-chart' |
      'torii-gate' |
      'file-slash' |
      'phone-lock-alt' |
      'phone-outgoing-alt' |
      'camera-alt-1' |
      'mail-refresh' |
      'lightbulb-exclamation-alt' |
      'mobile-slash' |
      'wallet-minus' |
      'capsule' |
      'message-circle-pencil' |
      'church' |
      'location-pin-slash' |
      'chevron-down-right' |
      'monitor-alt' |
      'watch-alt-1' |
      'clock-check' |
      'clock-desk' |
      'diamond-turn-right' |
      'sensor-on' |
      'toilet-paper-blank' |
      'chart-line-up' |
      'file-exclamation' |
      'laptop-signal' |
      'laptop-arrow-down-alt' |
      'mobile-alt-2' |
      'file-bookmark-alt' |
      'square-parking-slash' |
      'mail-alt-3' |
      'square-pen' |
      'temperature-arrow-up' |
      'bank' |
      'trademark' |
      'scan' |
      'chimney' |
      'percent' |
      'suitcase' |
      'credit-card-scan' |
      'wifi' |
      'eye-dropper-half' |
      'arrow-narrow-circle-broken-right' |
      'code' |
      'briefcase-medical' |
      'sparkles' |
      'paint-roller' |
      'chevron-selector-vertical-dot' |
      'paperclip-slash-alt' |
      'file-arrow-up-alt-1' |
      'presentation-chart-alt' |
      'align-center' |
      'circle-dollar-to-slot' |
      'potion' |
      'briefcase-alt' |
      'letter-english-a' |
      'cursor' |
      'star-exclamation' |
      'move-alt' |
      'phone-intercom' |
      'tenge-sign' |
      'printer' |
      'tughrik-sign' |
      'user-xmark' |
      'clock-two-thirty' |
      'money-check-dollar' |
      'usb-flash-drive-alt-1' |
      'mouse-alt-2' |
      'chart-tree-map' |
      'hotel' |
      'objects-align-center-horizontal' |
      'cloud-minus' |
      'podcast' |
      'mail-shield' |
      'mobile-xmark' |
      'diamond' |
      'wallet-plus' |
      'columns-2' |
      'modem-alt-2' |
      'address-book' |
      'send-alt-3' |
      'clock-one' |
      'mail-search' |
      'square-parking' |
      'phone-lock' |
      'drawing-tablet' |
      'tower-broadcast' |
      'dice-three' |
      'chart-pyramid' |
      'laptop-exclamation-alt' |
      'triangle-arrows-bolt' |
      'location-pin-lock' |
      'party-horn' |
      'grid' |
      'car' |
      'water-arrow-up' |
      'briefcase-alt-3' |
      'cloud-slash' |
      'place-of-worship' |
      'lock-slash' |
      'arrow-up-short-wide' |
      'left-to-right-text-direction' |
      'pause' |
      'calendar-circle-minus' |
      'play-pause' |
      'gift' |
      'magnet' |
      'clipboard-list-alt' |
      'clipboard-minus' |
      'lock-alt' |
      'video' |
      'arrow-narrow-circle-broken-down' |
      'phone-incoming-alt' |
      'mouse-alt-1' |
      'grip-lines' |
      'camera-alt' |
      'headphones-alt-1' |
      'fingerprint' |
      'distribute-spacing-vertical' |
      'message-square-heart' |
      'arrow-up-from-square' |
      'route' |
      'compress-alt-2' |
      'folder-search' |
      'coin' |
      'laptop-refresh' |
      'border-outer' |
      'arrow-down-right' |
      'notebook' |
      'tags' |
      'angel' |
      'file-chart-column' |
      'graduation-hat-alt-1' |
      'cloud-rain-alt' |
      'delete-left' |
      'arrow-square-up-right' |
      'id-card-clip' |
      'shredder' |
      'file-graph' |
      'file-search-alt-1' |
      'inbox-heart' |
      'pen-nib-slash' |
      'house-chimney-user' |
      'square-user-chart' |
      'refresh-ccw' |
      'trash-xmark' |
      'volume-minus' |
      'coin-alt' |
      'expand' |
      'slash-flip' |
      'engine-warning' |
      'marker' |
      'bus' |
      'tent-arrows-down' |
      'alarm-clock-alt' |
      'arrow-up-left' |
      'square-phone-flip' |
      'folder-block' |
      'high-definition' |
      'presentation-line' |
      'upload' |
      'circle-three-quarters' |
      'message-square' |
      'align-left-justify' |
      'corner-down-left' |
      'sunset' |
      'square-t' |
      'resize-handle' |
      'border-vertical' |
      'usb-flash-drive' |
      'camera-slash' |
      'webcam-alt' |
      'pound-circle' |
      'skates-alt' |
      'mug-sauser' |
      'medal-alt' |
      'bitcoin-circle' |
      'mail-open-check' |
      'file-shield-alt-1' |
      'chart-area' |
      'timer' |
      'caret-left-to-line' |
      'square-dollar' |
      'circle-plug-alt' |
      'train-subway' |
      'engine' |
      'circle-water-plug' |
      'clock-nine-thirty' |
      'corner-up-right' |
      'lock-hashtag' |
      'wand' |
      'microphone-slash-alt' |
      'arrow-circle-up-right' |
      'heart-half-stroke' |
      'file-shield-alt' |
      'refresh-cw-alt-4' |
      'mail' |
      'hurricane-alt-1' |
      'file-lock-alt-1' |
      'circle-pause' |
      'columns-3' |
      'house-medical' |
      'chart-simple-horizontal' |
      'briefcase-alt-4' |
      'basket-shopping' |
      'inbox-xmark' |
      'unlock-alt' |
      'pound-sign' |
      'cart-plus' |
      'disc-drive' |
      'trash-alt' |
      'diamond-exclamation' |
      'clock-two' |
      'container-storage' |
      'underline' |
      'candle-stand' |
      'wifi-weak' |
      'table-alt' |
      'user-heart-alt' |
      'clock-plus' |
      'chevron-right' |
      'house-turret' |
      'location-arrow' |
      'expand-alt' |
      'message-square-chat' |
      'paperclip' |
      'car-side' |
      'circle-waveform-lines' |
      'chevron-left' |
      'brackets-round' |
      'objects-align-left' |
      'mouse' |
      'arrow-up-from-arc' |
      'mobile' |
      'at-sign' |
      'exclamation-alt' |
      'folder' |
      'clock-three' |
      'temperature-arrow-down' |
      'crosshair' |
      'gear-alt' |
      'images-user' |
      'mobile-signal-out' |
      'square-dots-vertical' |
      'trash-arrow-up-alt' |
      'gauge-max' |
      'circle-quarter' |
      'arrow-up-1-9' |
      'strikethrough' |
      'circle-radiation' |
      'question' |
      'address-card' |
      'globe-alt' |
      'laptop-signal-alt' |
      'hexagon-image' |
      'mail-bookmark' |
      'mp3-player' |
      'map-pin' |
      'calendar-check' |
      'campground' |
      'align-right-justify' |
      'message-square-list' |
      'image-user' |
      'house-building' |
      'asterisk' |
      'arrow-narrow-left' |
      'landmark' |
      'cube' |
      'voicemail' |
      'message-square-lock' |
      'clock-minus' |
      'shield-keyhole' |
      'link-slash' |
      'temple' |
      'arrow-narrow-up' |
      'mobile-alt' |
      'house-medical-flag' |
      'signal-stream-slash' |
      'phone-outgoing' |
      'menu-alt' |
      'cent-sign' |
      'knife-kitchen' |
      'phone-alt' |
      'arrow-up' |
      'phone-office' |
      'flag' |
      'spell-check' |
      'user-shield-alt-1' |
      'microphone-slash' |
      'volume-plus' |
      'inbox' |
      'thermometer' |
      'toilet-paper-dots' |
      'book-section' |
      'camera' |
      'video-slash' |
      'basket-shopping-alt' |
      'circle-dollar' |
      'star-half-stroke' |
      'chevron-right-double' |
      'arrow-up-9-1' |
      'message-circle-lock' |
      'bluetooth-on' |
      'file-dollar' |
      'bracket-square' |
      'clock-slash' |
      'message-square-info' |
      'plus' |
      'mailbox-alt' |
      'arrow-down-arrow-up' |
      'file-arrow-left' |
      'circle-minus' |
      'loop' |
      'badge-check' |
      'circle-user' |
      'calendar-xmark-alt' |
      'video-arrow-up-right' |
      'location-exclamation' |
      'star-alt-1' |
      'send-alt' |
      'arrow-down-9-1' |
      'wind' |
      'microchip' |
      'cart-arrow-down' |
      'award' |
      'club' |
      'message-square-chart-lines' |
      'reply' |
      'browser' |
      'won-sign' |
      'font' |
      'gauge-high' |
      'square-cv' |
      'user-check-alt-1' |
      'mail-pencil' |
      'webcam' |
      'lines-leaning' |
      'thumbtack' |
      'text' |
      'file-arrow-down' |
      'image-polaroid-user' |
      'halloween-calendar-alt' |
      'clipboard-xmark' |
      'arrow-sm-up' |
      'diagram-predecessor' |
      'dots-horizontal-alt' |
      'letter-japanese-a' |
      'arrow-narrow-left-alignment' |
      'message-square-xmark' |
      'modem-alt-3' |
      'file-question' |
      'microphone-alt' |
      'briefcase-alt-1' |
      'rupee-sign' |
      'hat-wizard-alt' |
      'subdirectory' |
      'message-square-lines-alt' |
      'cart-check' |
      'vault' |
      'heart-alt' |
      'mouse-alt' |
      'dice-one' |
      'screencast' |
      'microphone' |
      'clone' |
      'file-info-alt-1' |
      'mail-notification' |
      'folder-heart' |
      'circle-notch' |
      'arrow-sm-left' |
      'message-square-arrow-up' |
      'droplets' |
      'user-search' |
      'credit-card-minus' |
      'temperature-sun' |
      'dial-max' |
      'calendar-plus' |
      'face-smile' |
      'santa-claus' |
      'icicles' |
      'phone-signal-alt' |
      'candy' |
      'eclipse' |
      'laptop-check-alt' |
      'square-sliders-vertical' |
      'user-refresh' |
      'monitor-alt-5' |
      'calendar-circle-exclamation' |
      'server' |
      'arrow-circle-up-left' |
      'message-circle-arrow-up' |
      'castle' |
      'coins-alt' |
      'grid-search' |
      'lasso-sparkles' |
      'gem' |
      'cart-minus' |
      'trash-undo' |
      'dial-off' |
      'circle' |
      'superscript' |
      'location-crosshairs-slash' |
      'briefcase-plus' |
      'hurricane-alt' |
      'message-circle-heart' |
      'simcard' |
      'cauldron' |
      'square-dots' |
      'link-slash-alt' |
      'cart-shopping-fast' |
      'loader' |
      'indent' |
      'shield-exclamation' |
      'menu-alt-2' |
      'file-minus' |
      'scribble' |
      'moneybag' |
      'heat-alt' |
      'stopwatch' |
      'arrow-square-down-left' |
      'bitcoin-sign' |
      'refresh-ccw-alt-4' |
      'inbox-arrow-right' |
      'refresh-cw-alt-2' |
      'globe-alt-1' |
      'gaming-pad-alt' |
      'arrow-down-short-wide' |
      'monitor-alt-4' |
      'user-refresh-alt' |
      'webcam-slash-alt' |
      'dazzle' |
      'square-quarters' |
      'modem-alt' |
      'building-arrow-right' |
      'circle-percentage' |
      'flip-forward-energy' |
      'lightbulb' |
      'piano' |
      'message-circle-lines-alt' |
      'cookies' |
      'monument' |
      'cloud-fog' |
      'forward-step' |
      'calendar-lines' |
      'volume-max' |
      'badge-dollar' |
      'cloud-music' |
      'key-alt' |
      'wallet-alt' |
      'chart-bullet' |
      'map-pin-alt' |
      'graduation-hat-alt-2' |
      'laptop-arrow-down' |
      'dollar-sign' |
      'clipboard-arrow-up' |
      'play' |
      'house-shield' |
      'caret-left' |
      'circuit' |
      'file-xmark' |
      'phone-flip-alt' |
      'gem-alt' |
      'repeat' |
      'dice-two' |
      'inbox-minus' |
      'id-card' |
      'building-check' |
      'tower' |
      'menorah-alt' |
      'memo-check' |
      'objects-align-top' |
      'tablet-alt-2' |
      'building-flag' |
      'square-code' |
      'scarecrow' |
      'mail-arrow-down' |
      'eye-slash' |
      'file-arrow-down-alt-1' |
      'music' |
      'phone-missed' |
      'tv' |
      'distribute-spacing-horizontal' |
      'circle-check' |
      'halloween-decorations' |
      'shield-slash-alt' |
      'bars-progress' |
      'restaurant-menu' |
      'file-wired' |
      'message-circle-info' |
      'sleigh' |
      'keyboard-alt-1' |
      'clouds' |
      'search-alt-2' |
      'cursor-alt' |
      'file-exclamation-alt-1' |
      'chevron-left-double' |
      'modem' |
      'house-user' |
      'grid-dividers' |
      'folder-shield' |
      'cube-alt-2' |
      'list-ul-alt' |
      'arrow-up-right-from-square' |
      'text-size' |
      'graduation-hat-alt' |
      'align-letter-right' |
      'house-water' |
      'triangle' |
      'pen-slash' |
      'calendar-lines-pen' |
      'file-heart-alt-1' |
      'circle-heart' |
      'microphone-slash-alt-1' |
      'crosshair-simple' |
      'square-list' |
      'expand-wide' |
      'trash-list-alt' |
      'shield-alt' |
      'chart-column' |
      'landmark-flag' |
      'house-medical-xmark' |
      'code-alt' |
      'cloud-rain-alt-1' |
      'sort-up' |
      'snow' |
      'align-center-alt' |
      'house-medical-exclamation' |
      'microphone-alt-1' |
      'tablet' |
      'arrow-narrow-circle-broken-down-left' |
      'arrow-down' |
      'chevron-down' |
      'pen-swirl' |
      'eye' |
      'objects-align-center-horizontal-alt' |
      'right-to-left-text-direction' |
      'refresh-ccw-alt-3' |
      'caret-down' |
      'chevron-down-left' |
      'cloud-moon' |
      'rss' |
      'candle-holder' |
      'diagram-venn' |
      'italic' |
      'keyboard' |
      'figma' |
      'alarm-clock' |
      'table-layout' |
      'arrow-circle-left' |
      'xmark' |
      'stars' |
      'cloud-arrow-down-alt' |
      'image-pen' |
      'dialpad-circle' |
      'tombstone' |
      'signal' |
      'circle-question' |
      'gear' |
      'mail-open-arrow-down' |
      'airpods' |
      'cart-xmark' |
      'file-cv' |
      'ornament-alt' |
      'video-plus' |
      'diagram-cells' |
      'tag' |
      'tree-decorated' |
      'compress-alt' |
      'cloud-plus' |
      'corner-right-down' |
      'circle-plus' |
      'cart-arrow-up' |
      'fork-knife' |
      'sort-amount-down' |
      'file-audio' |
      'pen-line' |
      'objects-align-bottom' |
      'shield-alt-1' |
      'move' |
      'mail-alt-2' |
      'inbox-arrow-left' |
      'toilet-portable' |
      'shield-plus' |
      'shield-bolt' |
      'right-indent' |
      'traffic-cone' |
      'hockey-mask' |
      'lock-a' |
      'mail-alt-1' |
      'document-layout-left' |
      'clock-snooze' |
      'trash-slash-alt' |
      'user-minus' |
      'receipt-alt-3' |
      'mail-open' |
      'alarm-plus' |
      'kerning' |
      'hospital' |
      'stopwatch-10' |
      'euro-sign' |
      'eye-dropper' |
      'wand-sparkles' |
      'align-right' |
      'bell-alt-1' |
      'candy-alt' |
      'phone-incoming' |
      'tally' |
      'user-block-alt' |
      'album' |
      'chevron-up-double' |
      'mail-open-alt-1' |
      'chevron-up-right' |
      'brake-warning' |
      'arrow-up-from-bracket' |
      'arrow-down-big-small' |
      'phone-call-alt-1' |
      'user-check-alt' |
      'list' |
      'ticket-simple' |
      'arrow-down-to-arc' |
      'terminal' |
      'globe-dollar' |
      'chart-scatter-bubble' |
      'circle-half-stroke' |
      'house-sun' |
      'search' |
      'money-stack' |
      'monitor-alt-3' |
      'diagram-project-1' |
      'turn-off' |
      'clock-five-thirty' |
      'phone-signal';

    type iconColors = '#000000';

    type backgroundType = 'circle' | 'rect' | 'button';

    type colorsType = Record<iconColors, string>;

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      colors: colorsType;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      colors?: colorsType;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
